README.md, action.yml, entrypoint.sh
Addresses issue mentioned here https://github.com/crowdin/github-action/issues/2
=> Add pre-config option

README.md
This PR updates the README to clarify the changes that need to made to the `crowdin.yml` configuration file.
See https://github.com/crowdin/github-action/issues/7#issuecomment-623061619
cc @og-fox @VBeytok
=> docs: mention crowdin.yml requirements

README.md, action.yml, entrypoint.sh
Add new variables for upload translations
from https://support.crowdin.com/configuration-file/
=> Add more options for upload translations

README.md, entrypoint.sh
=> fix bug with PR on schedule

entrypoint.sh
=> improve created PR output

Dockerfile, README.md, action.yml, entrypoint.sh
update version cli and remove --import-duplicates(not supported) option from upload translations
=> update version cli and remove --import-duplicates option

README.md, action.yml, entrypoint.sh
option for add labels to created PR
resolve issue https://github.com/crowdin/github-action/issues/18
=> add pull_request_labels

README.md, action.yml, entrypoint.sh
resolve issue https://github.com/crowdin/github-action/issues/20
=> add options commit_message, pull_request_title, pull_request_body

README.md, action.yml, entrypoint.sh
- Base URLs for GitHub server and API.
- GitHub user overrides for specifying a valid user.
Resolves https://github.com/crowdin/github-action/issues/78
=> Add configuration options to support GitHub Enterprise.

README.md, action.yml, entrypoint.sh
=> add support for additional arguments

entrypoint.sh
Fix git checkout when workflow triggered from pull request #66
=> Correct trigger workflow from pull request

Dockerfile, README.md
- update CLI version to [3.7.9](https://github.com/crowdin/crowdin-cli/pull/437)
=> Version 1.4.10

README.md, action.yml, entrypoint.sh
=> make gpg_passphrase not required

Dockerfile, README.md
=> Version 1.4.13

README.md, action.yml, entrypoint.sh
Done! I have already tested it and works perfectly! Let me know if it looks good for you. 
Also, I think that you could open an issue for adding team reviewers to a pull request. It would be a great feature. I know is possible but I'm not sure how to do it the best way possible with bash.
=> Add reviewer(s) when creating a pull-request

entrypoint.sh
=> fix: pull request existence condition

entrypoint.sh
=> fix(#207): Empty out the pull_request_url for real

EXAMPLES.md, README.md, action.yml, entrypoint.sh
=> feat: add the 'pull_request_number' output

README.md
Improved documentation on the secrets needed and where to find them.
=> docs: Improved documentation for secrets

entrypoint.sh
=> fix: issues related to checking for the existing pull requests

README.md
=> docs: default values

EXAMPLES.md, README.md
=> docs: provide more details on some frequent topics
