crowdin/github-action

- README.md
This PR updates the documentation in the README to clarify that the project ID and token should be from the V2 API, not the old "project identifier" and "API key" from V1.
Resolves #5 (maybe)
cc @Bartlebyy
> docs: clarify project_id and token in README

- README.md
This PR adds some documentation to clarify the difference between `localization_branch_name` and `crowdin_branch_name`.
Resolves #10
> docs: clarify branch types

- entrypoint.sh
Hey.
According to the source of `entrypoint.sh`, `GITHUB_TOKEN` is used only for `push_to_branch()` routine which is **not** called when `push_translations` is set to `false`. Therefore, it shouldn't be required to specify github token in this case, as it's not used at all, even if provided.
This follows on existing expectation of not requiring `GITHUB_TOKEN` e.g. for uploading, which also doesn't use the token anywhere.
Thank you for considering this enhancement.
> Skip github token check when not pushing

- README.md
- action.yml
- entrypoint.sh
This adds possibility to maintain different translations sets
for different project branches.
Currently you can create separate workflows for separate branches,
and use different localization branches for them,
but it will always create pull request to default selected branch.
This commit allows to override base branch using default branch
when this options isn't specified
> Add possibility to configure base branch

- entrypoint.sh
When using [githooks](https://git-scm.com/docs/githooks), the action will sometimes fail because it can't find a specified file ([in our case](https://github.com/wireapp/wire-webapp/runs/1886243058#step:9:83), it was `npx`).
This will use git's `--no-verify` option to ignore githooks.
> fix: Ignore githooks

- Dockerfile
- action.yml
- entrypoint.sh
Support signed commits by importing a private key from secrets into the gpg keystore on the fly.
> Support commit signing

- README.md
- entrypoint.sh
Minor changes regarding signing commits.
- fixes an issue when GPG key id starts with a letter it can't be imported
- updated README about using the signed commits feature
- assuming this will be version 1.3.1, specified it in the instructions
> Bugfix for GPG key import

- entrypoint.sh
Github documentation reference: https://docs.github.com/en/rest/reference/pulls#list-pull-requests
`GET /repos/{owner}/{repo}/pulls` does not take a JSON body. Instead, the options must be sent as query parameters.
> fix incorrect params for GET /pulls

- Dockerfile
- README.md
- action.yml
- entrypoint.sh
> add option for add and delete branch in crowdin and update cli version

- entrypoint.sh
Hello Crowdin folks!
The reason for that is that some users may want to remove all
translation before downloading them again, for instance, to make sure
there are no stale translations.
When that is the case, the first check will indicate there are changes,
since files were removed.
However, when the download files are the same as the files that were
previously removed, `git add .` will cause the next `git status -s` to
be clean. If the second check is not in place, the script will attempt
to commit the changes, but as there are none, the action will fail,
instead of just being skipped.
Snippet of a config we are using:
```yaml
name: Crowdin Sync
on:
push:
branches: [main]
jobs:
sync_with_crowdin:
name: Sync with Crowdin
if: github.repository == 'github/docs-internal-downsized'
runs-on: …
```
> Check status once again before committing

- entrypoint.sh
The GitHub Action fails to create a pull request due to Git v2.35.2 spec changes.
More info and should fix https://github.com/crowdin/github-action/issues/114
I have tested my fork in a private repository and it worked as expected after this patch.
> Fix for Git v2.35.2 spec changes

- README.md
- action.yml
Hey there, 
I was setting up my crowdin github actions and noticed this, so I thought I'd update the descriptions. 😊
The action failed when starting with a "/". For example:
`source: "/src/i18n/languages/en/**/*.*"` - action failed ❌
Removing the "/" solved it:
`source: "src/i18n/languages/en/**/*.*"` - works! ✅
* Same thing for the `base_path` as well.
> Updated descriptions for base_path and source

- README.md
- action.yml
- entrypoint.sh
Opening this to get feedback on the addition of a new option `pull_request_assignees` which will assign the created pull request to users. This is based on the label functionality added in https://github.com/crowdin/github-action/pull/25 by @VBeytok 🙂  
The use-case is adding specific assignees that will review the created pull request. A workaround without this functionality is to use a [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax) file.
This is optional, if this doesn't add value please feel free to close this PR; otherwise happy to discuss any improvements to the code, the `create_pull_request` function is getting pretty large at this point.
> Assign users to PR via pull_request_assignees

- entrypoint.sh
This adds an authentication check before attempting to create a pull request via the action. If the check fails we do not proceed to create a pull request. It provides a useful error message when reviewing the action logs.
When running this action I noticed the following error when a `GITHUB_TOKEN` expires:
```
jq: error (at <stdin>:4): Cannot index string with string "head"
```
This is caused by an attempt to get the head ref when the API responds with an error:
```
{ "message": "Bad credentials", "documentation_url": "https://docs.github.com/rest" }
```
https://github.com/crowdin/github-action/blob/ec22a497e86e368978394007ad718f9bbfdc396c/entrypoint.sh#L100
> Add authentication check

- .github/workflows/update-main-version.yml
- Dockerfile
- EXAMPLES.md
- README.md
- Bump CLI version
- Add 'update-main-version' GitHub Workflow
- Use the 'v1' version in the examples
> Version v1.6.0

- EXAMPLES.md
- README.md
- action.yml
- entrypoint.sh
This PR adds the new input argument `pull_request_team_reviewers`.  [GitHub's API to request reviewers takes different arguments for users and teams](https://docs.github.com/en/rest/pulls/review-requests?apiVersion=2022-11-28#request-reviewers-for-a-pull-request), for example:
```
curl -L \
-X POST \
-H "Accept: application/vnd.github+json" \
-H "Authorization: Bearer <YOUR-TOKEN>" \
-H "X-GitHub-Api-Version: 2022-11-28" \
https://api.github.com/repos/OWNER/REPO/pulls/PULL_NUMBER/requested_reviewers \
-d '{"reviewers":["octocat","hubot","other_user"],"team_reviewers":["justice-league"]}'
```
With these changes, PRs opened by this action can now have requested reviews from users and/or teams. Both are optional. 
Documentation has also been updated to include the new argument.
> feat: add support for team review requests

- entrypoint.sh
Currently if the PR title passed as a parameter as a double quote the action will fail when calling GitHub's API to create the pull request.
This uses jq to make sure the generated JSON is valid by properly escaping the variables.
> fix: allow PR titles to contain double quotes

- README.md
- action.yml
- entrypoint.sh
I'm suggesting adding this output to the action for the following reasons:
When a pull request is created using the API, it does not trigger workflows listening on `pull_request`. The only way to get around this is by doing a repository dispatch and pick up on that in stead. With the added output this should be a bit more straight forward in the workflow that uses `crowdin/github-action`. 
I did not add the output in the README, as this is the first output added to the action altogether.
> feat: add output letting users know if a pull request was created or not

- entrypoint.sh
If you download both sources and translations in your workflow then the output would be overridden the second time around as the pull request already exists!
Avoid this by 1) setting a default value in the start of the script and 2) only adjust the output if its non empty.
> fix: pull_request_url output overriden if downloading sources and translations

- README.md
In the section that describes the required permissions for the GITHUB_ACTIONS token, "Contents" is misspelled as "Content" (missing an 's').
The table of all valid permissions can be found here: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
> docs: fix typo 'content' for GITHUB_TOKEN permission

- action.yml
This option doesn't make much sense in the context of the GitHub action, where environment variables are a de facto standard for credentials loading. It's marked as deprecated and will be removed in the next major release.
> chore: deprecate the 'identity' option

- entrypoint.sh
Fixes: https://github.com/crowdin/github-action/issues/242
Uses `GITHUB_HEAD_REF` if available (which points to the head on `pull_request` event triggers) and falls back to `${GITHUB_REF#refs/heads/}` or `${GITHUB_REF#refs/tags/}` otherwise.
[As per the docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables), `GITHUB_REF` has 3 possible values:
- `refs/pull/<pr_number>/merge`: `pull_request` events where `GITHUB_HEAD_REF` is set to the actual head
- `refs/tags/<tag_name>`: `release` events, this PR extracts the tag_name and checks that out
- `refs/heads/<branch_name>`: all other events such as `push`
> fix: check out correct branch on pull_request events

- entrypoint.sh
@andrii-bodnar May I suggest this? It's what I meant [here](https://github.com/crowdin/github-action/issues/270#issuecomment-2939594824).
> fix: Use GH_TOKEN instead of GITHUB_APP_TOKEN
